import "reflect-metadata";
import { AppDataSource } from "./data-source";
import { User } from "./entities/User";
import { Post } from "./entities/Post";

async function main() {
  try {
    // Initialize the database connection
    await AppDataSource.initialize();
    console.log("✅ Database connected!\n");

    // Show migration status
    console.log("📋 Checking migration status...\n");

    const queryRunner = AppDataSource.createQueryRunner();

    // Check if migrations table exists
    const migrationsTableExists = await queryRunner.hasTable("migrations");

    if (!migrationsTableExists) {
      console.log("⚠️  No migrations have been run yet.");
      console.log("   Run: pnpm migration:run\n");
    } else {
      // Get executed migrations
      const executedMigrations = await queryRunner.query(
        `SELECT * FROM "migrations" ORDER BY "timestamp" DESC`
      );

      if (executedMigrations.length > 0) {
        console.log("✅ Executed migrations:");
        executedMigrations.forEach((m: { name: string; timestamp: number }) => {
          console.log(`   - ${m.name}`);
        });
        console.log();
      }
    }

    await queryRunner.release();

    // Demo: Check if tables exist and show counts
    console.log("📊 Database Statistics:\n");

    try {
      const userCount = await AppDataSource.getRepository(User).count();
      console.log(`   Users: ${userCount}`);
    } catch {
      console.log("   Users table: Not created yet");
    }

    try {
      const postCount = await AppDataSource.getRepository(Post).count();
      console.log(`   Posts: ${postCount}`);
    } catch {
      console.log("   Posts table: Not created yet");
    }

    console.log("\n" + "=".repeat(50));
    console.log("TypeORM CLI Commands Reference:");
    console.log("=".repeat(50));
    console.log(`
1. CREATE a new empty migration:
   pnpm migration:create src/migrations/MyNewMigration

2. GENERATE migration from entity changes:
   pnpm migration:generate src/migrations/AutoGenerated

3. RUN pending migrations:
   pnpm migration:run

4. REVERT the last migration:
   pnpm migration:revert

5. SHOW migration status:
   pnpm migration:show

6. SYNC schema (development only!):
   pnpm schema:sync

7. DROP all tables:
   pnpm schema:drop

8. LOG SQL that would be executed:
   pnpm schema:log
`);
  } catch (error) {
    console.error("❌ Error:", error);
  } finally {
    if (AppDataSource.isInitialized) {
      await AppDataSource.destroy();
      console.log("\n👋 Database connection closed.");
    }
  }
}

main();
